### ISSUE TITLE
Extended titles after Disc not supported

### ISSUE THREAD

**Issue by birdybro** [tralph3/PSX-Cue-Maker#8]
I realize this doesn't fit your naming scheme, but it appears that many files have this naming scheme as well from redump.

![image](https://user-images.githubusercontent.com/16388068/94095475-0adcd380-fddf-11ea-941f-233fafceced1.png)

It treated each of these as seperate games, instead of different discs, due to the naming scheme after (Disc). Perhaps ignore anything before and after disc that isn't Rev etc..?

This is the redump datfile naming scheme still (weird for these). Figured I'd bring this up in case you were interested.

**Comment by tralph3** [comment]
It's treating them differently not because there's something after the disc portion, but because if you remove the disc portion the names are different. The script detects multi-disc games by removing the disc part and seeing if the names match, if there's further differences they will be treated as different games, and making exceptions for that would just be a mess. This is, sadly, intended functionality. I could try to make it ignore everything after disc... but then that may introduce issues with the track files. I'll take a quick look and see if it can be introduced.

**Comment by birdybro** [comment]
Yup, that's what I assumed, that it was intended. No biggie, it's just more real-world testing behavior I wanted to show ya :)

**Comment by tralph3** [comment]
[cuemaker.zip](https://github.com/tralph3/Cue-Maker/files/5273288/cuemaker.zip)
I made a quick modification that should ignore everything after the disc part, I didn't test it but it *shouldn't* have issues, only that if there's Region indicators after the disc they will be all merged into the same game and such... I won't commit this, but you can use it for yourself. **It may cause issues**, but I'm more confident in that it will work than not.
